### ISSUE TITLE
Not supported in Architect v6?

### ISSUE THREAD

**Issue by alexbepple** [architect/plugin-node-prune#7]
This does nothing in Architect v6, correct?

Any plans on supporting `@plugins` again? Or should I just remove this from `.arc` and `package.json`?

**Comment by ryanblock** [comment]
Didn’t realize anyone but us was using this! :)

Impeccable timing though, was just talking in our Slack about porting this to Arc 6 Macros. Give me a couple days!

**Comment by alexbepple** [comment]
😁 No hurry.

**Comment by ryanblock** [comment]
[1.0.0](https://www.npmjs.com/package/@architect/arc-macro-node-prune) now live! Please `npm i @architect/arc-macro-node-prune` and add to your Architect (v6) project manifest:
```
@macros
architect/arc-macro-node-prune
```

Made some nice result printing improvements along the way, lmk what you think!

**Comment by alexbepple** [comment]
@ryanblock Unfortunately, this did nothing for my function size. :( I believe that the plugin (with Architect v5) was more helpful on this particular project.

It was weird, though, that adding the macro at first increased my function sizes. Only after I deleted all `node_modules` in the tree, `hydrate`d and re-added this macro, did I get back to the size I had before. Are you aware of any weirdness that would lead to function sizes growing without any apparent reason?

**Comment by ryanblock** [comment]
Ah ha! We changed the order in which we do pre-deploy operations, hydration now occurs after macros, so that cleanup is neutralized. Ha. Should be a quick fix, please  stand by!

**Comment by ryanblock** [comment]
Sorry for the lag, things have been a bit hectic! It's now live in Architect `6.2.5`, let me know how it goes!
